version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/task_db
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    command: sh -c "pnpm install && npx prisma migrate dev && npx prisma generate && pnpm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "pnpm install && pnpm run dev"

volumes:
  postgres_data:
